<?php

use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\Exceptions;
use Illuminate\Foundation\Configuration\Middleware;

return Application::configure(basePath: dirname(__DIR__))
    ->withRouting(
        web: __DIR__.'/../routes/web.php',
        api: __DIR__.'/../routes/api.php',
        commands: __DIR__.'/../routes/console.php',
        health: '/up',
    )
    ->withMiddleware(function (Middleware $middleware): void {
        // 0. Custom domain resolution — runs FIRST so that the host header
        //    is checked before route matching. If a gallery is resolved,
        //    GalleryViewController will render it regardless of the URL path.
        $middleware->prepend(\App\Http\Middleware\DetectCustomDomain::class);

        // A-9 FIX (Iter-006): Assign a per-request UUID early, before anything
        // else runs, so it's available in logs/Sentry for the whole request.
        $middleware->prepend(\App\Http\Middleware\RequestId::class);

        // 0b. Exempt 2Checkout IPN webhook routes from CSRF protection.
        //     SEC-3 FIX: Tightened from 'webhooks/*' (matches ANY path under
        //     webhooks/) to the exact two routes that 2Checkout uses.
        //
        //     Iter-007 (RFC 8058): Also exempt the one-click unsubscribe
        //     POST route. Gmail/Yahoo's automated unsubscribe machinery
        //     POSTs to this URL without a CSRF token (it's not a browser
        //     request). The `signed` middleware on the route verifies the
        //     HMAC signature, which is the only auth needed — the URL was
        //     generated by the app and embedded in the email header, so
        //     only the legitimate recipient's email client hits it.
        $middleware->validateCsrfTokens(except: [
            'webhooks/2checkout',
            'webhooks/2checkout/refund',
            'unsubscribe/one-click/*',
        ]);

        // 0a. Scope session cookie domain to the request host — runs BEFORE
        //     the session middleware so config('session.domain') is set
        //     correctly when the cookie is baked. Fixes the PIN-session
        //     bug on custom-domain requests (Round 3).
        $middleware->prepend(\App\Http\Middleware\ScopeSessionDomain::class);

        // 1. Security Headers
        $middleware->append(\App\Http\Middleware\SecurityHeaders::class);

        // 2. Banned users check — runs on every authenticated request
        $middleware->append(\App\Http\Middleware\CheckBanned::class);

        // 3. Plan expiry check — auto-downgrades expired paid plans
        $middleware->append(\App\Http\Middleware\CheckPlanExpiry::class);

        // 4. Trusted proxies — restrict to the actual reverse-proxy network
        //    instead of trusting every caller. (Task C17)
        //
        //    WHY: `trustProxies(at: '*')` trusts any client's
        //    X-Forwarded-Host / X-Forwarded-Proto / X-Forwarded-For headers.
        //    An attacker who can reach the app directly (bypassing Coolify's
        //    Traefik) can spoof these headers — enabling host-header session
        //    attacks (ScopeSessionDomain reads $request->getHost()), custom-
        //    domain spoofing (DetectCustomDomain reads $request->getHost()),
        //    and IP-spoofing (which weakens rate limiting and audit logging).
        //
        //    The TRUSTED_PROXIES env var should be set in production to
        //    Coolify's internal docker network (typically 172.16.0.0/12 or
        //    the specific Traefik container IP). Find it via:
        //       docker network inspect coolify-network | grep Subnet
        //
        //    Acceptable values:
        //      - specific IPs: "10.0.0.5,10.0.0.6"
        //      - CIDR ranges: "172.16.0.0/12"
        //      - "*" (legacy permissive — PreflightCheck logs a warning)
        //
        //    SEC-1 FIX: Default changed from '*' to null (fail-closed).
        //    If TRUSTED_PROXIES is not set, Laravel trusts NO proxies.
        //    Behind Coolify/Traefik, set TRUSTED_PROXIES to the Traefik
        //    subnet (e.g. "10.0.1.0/24") for correct IP detection.
        //
        //    BOOTSTRAP-SAFETY FIX: The previous version called
        //    Log::critical() here when TRUSTED_PROXIES=*. That breaks
        //    `php artisan package:discover` and every artisan command
        //    during local development / fresh installs, because the Log
        //    facade is not yet bound to the container during the bootstrap
        //    phase. The deferred-provider resolution chain ends up
        //    trying to resolve the `env` binding, which doesn't exist
        //    yet, producing: "Target class [env] does not exist".
        //
        //    The warning for TRUSTED_PROXIES=* is now handled at runtime
        //    by App\Providers\AppServiceProvider::boot() and by the
        //    PreflightCheck artisan command — both of which run after
        //    the container is fully booted and the Log facade is safe
        //    to use.
        $trustedProxies = env('TRUSTED_PROXIES');
        if ($trustedProxies && $trustedProxies !== '*') {
            $middleware->trustProxies(at: $trustedProxies);
        } elseif ($trustedProxies === '*') {
            // Permissive mode — warn later (AppServiceProvider / PreflightCheck).
            $middleware->trustProxies(at: '*');
        }
        // If null/empty: trust no proxies (fail-closed)

        // 5. Middleware aliases
        $middleware->alias([
            'super_admin'   => \App\Http\Middleware\EnsureUserIsSuperAdmin::class,
            'mfa'           => \App\Http\Middleware\RequireMfa::class, // (Task H56)
            'feature_flag'  => \App\Http\Middleware\EnsureFeatureFlagEnabled::class, // M-14
        ]);
    })
    ->withExceptions(function (Exceptions $exceptions): void {
        //
    })->create();