<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * M-10 FIX: Create invoices table for customer invoicing (PDF).
 *
 * Each successful payment (one-time purchase OR recurring renewal) gets
 * an invoice record + a generated PDF. The PDF is stored on the public
 * disk and downloadable from the billing portal.
 *
 * Tax compliance: many jurisdictions (EU VAT, UK VAT, Australian GST,
 * etc.) require businesses to issue invoices with specific fields. This
 * table stores the fields needed for a compliant invoice:
 *   - invoice_number: sequential, unique, human-readable (e.g. INV-2026-00001)
 *   - tax_amount: the tax/VAT portion of the payment (0 if no tax applies)
 *   - tax_rate: the percentage applied (e.g. 20 for UK VAT)
 *   - billing_address: the customer's billing address (for B2B invoicing)
 *
 * The PDF is generated by InvoiceGenerator service and stored at
 * pdf_path. The path is relative to the public disk root.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('invoices', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained()->onDelete('cascade');
            // No ->constrained() here: MySQL/InnoDB forbids foreign keys
            // pointing at a partitioned table (error 1506, unconditional —
            // see 2026_07_04_000001_partition_transactions_by_month). The
            // column + index below still give fast lookups/joins;
            // referential integrity for transaction_id is enforced in
            // application code instead.
            $table->foreignId('transaction_id')->nullable();

            // Human-readable invoice number (e.g. INV-2026-00001).
            // Sequential per year, unique across the whole table.
            $table->string('invoice_number')->unique();

            // Financial details (mirrored from the transaction for historical
            // accuracy — even if the transaction is later anonymized by
            // SEC-10, the invoice retains the financial record).
            $table->decimal('amount', 10, 2);
            $table->decimal('tax_amount', 10, 2)->default(0);
            $table->decimal('tax_rate', 5, 2)->default(0); // e.g. 20.00 for 20% VAT
            $table->string('currency', 10)->default('USD');
            $table->string('plan');

            // Customer details at time of purchase (for B2B invoicing).
            $table->string('customer_name')->nullable();
            $table->string('customer_email');
            $table->text('billing_address')->nullable();

            // PDF storage path (relative to public disk root).
            // e.g. "invoices/2026/INV-2026-00001.pdf"
            $table->string('pdf_path')->nullable();

            $table->timestamp('issued_at');
            $table->timestamps();

            $table->index('user_id');
            $table->index('transaction_id');
            $table->index('issued_at');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('invoices');
    }
};
