<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\View\View;

/**
 * P0-3 FIX (audit): One-click unsubscribe endpoint for marketing emails.
 *
 * Iteration-007 (audit issues 9 + 10): Added RFC 8058 one-click POST
 * endpoint at /unsubscribe/one-click/{user}. This endpoint:
 *   - Is excluded from CSRF verification (VerifyCsrfToken middleware).
 *   - Verifies the signed URL (HMAC with APP_KEY) — equivalent to auth.
 *   - Sets marketing_consent = false.
 *   - Returns HTTP 200 (RFC 8058 §3 requires 2xx response).
 *   - Accepts both GET (browser visit) and POST (Gmail/Yahoo automated).
 *
 * Why a separate endpoint from the existing two-step flow:
 *   - The existing /unsubscribe/{user} GET shows a CONFIRMATION PAGE.
 *     A user who clicks the email footer link sees "Are you sure?"
 *     and must click Confirm. This is the human-friendly flow.
 *   - RFC 8058 says Gmail/Yahoo will POST to the List-Unsubscribe URL
 *     WITHOUT user interaction (when the user clicks "Unsubscribe" in
 *     the Gmail UI, Gmail sends a POST and expects a 200). This MUST
 *     NOT require a confirmation step — Gmail will not render the
 *     confirmation page.
 *   - The same signed URL works for both: a human clicking the footer
 *     link hits the GET (sees confirmation); Gmail's automated POST
 *     hits the POST (immediate unsubscribe + 200).
 *
 * CAN-SPAM §316.4 requires "a clear and conspicuous explanation of how
 * the recipient can opt out" in every commercial email. GDPR Art. 21
 * requires the right to object to marketing processing.
 *
 * The unsubscribe link in every marketing email points here:
 *   GET /unsubscribe/{user}?signature=...  → confirmation page (existing)
 *   POST /unsubscribe/{user}               → confirm (existing, requires signed URL)
 *   GET /unsubscribe/one-click/{user}?signature=... → one-click landing (new)
 *   POST /unsubscribe/one-click/{user}?signature=... → RFC 8058 one-click (new)
 *
 * All routes are protected by Laravel's `signed` middleware — the signature
 * is HMAC-signed with the APP_KEY, so only the app can generate valid
 * unsubscribe links. An attacker cannot forge a link to unsubscribe
 * another user.
 *
 * Flow (existing two-step for visible footer link):
 *   1. Email recipient clicks the unsubscribe link.
 *   2. The `signed` middleware verifies the signature.
 *   3. This controller shows a confirmation page (GET) — the user sees
 *      "You're about to unsubscribe" with a confirm button.
 *   4. The user clicks "Confirm" → POST /unsubscribe/{user} sets
 *      marketing_consent = false.
 *   5. The user sees "You've been unsubscribed" confirmation.
 *
 * Flow (RFC 8058 one-click for Gmail/Yahoo):
 *   1. User clicks "Unsubscribe" in Gmail's UI.
 *   2. Gmail POSTs to the List-Unsubscribe URL.
 *   3. The `signed` middleware verifies the signature.
 *   4. This controller sets marketing_consent = false.
 *   5. Returns HTTP 200 (RFC 8058 §3).
 *   6. (Optional) User visits the same URL in a browser and sees the
 *      "unsubscribed" confirmation page.
 */
class UnsubscribeController extends Controller
{
    /**
     * Show the unsubscribe confirmation page.
     * The route middleware ('signed') has already verified the signature.
     */
    public function show(Request $request, User $user): View
    {
        // If already unsubscribed, show a friendly "already unsubscribed" page.
        if (! $user->marketing_consent) {
            return view('unsubscribe', [
                'user'     => $user,
                'already'  => true,
            ]);
        }

        return view('unsubscribe', [
            'user'     => $user,
            'already'  => false,
        ]);
    }

    /**
     * Process the unsubscribe confirmation.
     * Sets marketing_consent = false on the user.
     */
    public function confirm(Request $request, User $user): RedirectResponse
    {
        $user->forceFill(['marketing_consent' => false])->save();

        return redirect()->route('unsubscribe.done')
                         ->with('status', 'unsubscribed');
    }

    /**
     * Iteration-007 (RFC 8058): One-click unsubscribe landing page (GET).
     *
     * Same signed URL as the POST endpoint, but accessible via browser.
     * A user who copies the List-Unsubscribe URL into a browser sees a
     * simple "You have been unsubscribed" page. No confirmation step —
     * the GET itself performs the unsubscribe, since the signed URL
     * already proves the user's intent (the URL was generated by the
     * app and only ever embedded in their own email).
     *
     * Why no confirmation here (unlike the /unsubscribe/{user} flow):
     *   - The List-Unsubscribe URL is in an HTTP header, not the email
     *     body. It is never pre-fetched by anti-phishing scanners (they
     *     only pre-fetch body links). The risk of accidental unsubscribe
     *     is essentially zero.
     *   - RFC 8058 expects a single round-trip: user clicks Gmail's
     *     "Unsubscribe" → done. A confirmation step would defeat the
     *     purpose.
     */
    public function oneClickShow(Request $request, User $user): View
    {
        // Perform the unsubscribe immediately. The signed URL is the
        // proof of intent — same as the POST handler below.
        if ($user->marketing_consent) {
            $user->forceFill(['marketing_consent' => false])->save();
        }

        // Show a plain confirmation page (no session dependency — the
        // page is self-contained so it works for users with cookie
        // blockers / strict browsers).
        return view('unsubscribe-done', ['valid' => true]);
    }

    /**
     * Iteration-007 (RFC 8058): One-click unsubscribe POST endpoint.
     *
     * This is the endpoint Gmail/Yahoo POST to when a user clicks the
     * "Unsubscribe" button in their email UI. The route is excluded
     * from CSRF verification (see bootstrap/app.php). The `signed`
     * middleware verifies the URL signature — that's the only auth.
     *
     * RFC 8058 §3: The server MUST respond with a 2xx status code on
     * success. We return 200 with an empty body. Gmail considers any
     * 2xx a successful unsubscribe.
     */
    public function oneClickPost(Request $request, User $user): Response
    {
        if ($user->marketing_consent) {
            $user->forceFill(['marketing_consent' => false])->save();
        }

        // RFC 8058 §3: "The response SHOULD be 200 OK." Empty body —
        // Gmail does not render it to the user.
        return response('', 200);
    }

    /**
     * Show the "You've been unsubscribed" confirmation page.
     */
    public function done(Request $request): View
    {
        $status = session('status');

        // Only show the success page if the user came from the confirm flow
        // (which sets 'status' => 'unsubscribed' in the session).
        // Direct access to /unsubscribe-done without the session flag shows
        // an "invalid request" page.
        if (! in_array($status, ['unsubscribed', 'already_unsubscribed'], true)) {
            return view('unsubscribe-done', ['valid' => false]);
        }

        return view('unsubscribe-done', ['valid' => true]);
    }
}
