{{-- RESET-ITERATION FIX: branded password-reset email. Uses the shared
    table-based layout (Outlook/Gmail compatible, inline CSS) like every
    other Exospace transactional email. The reset URL is generated by
    Laravel's password broker (App\Notifications\Auth\ResetPassword) and is
    passed in ready-to-use — this view never builds URLs itself. --}}
@extends('emails.partials.layout')

@section('title', 'Reset Your Password')

@section('preheader')
    {{-- Hidden but visible in inbox preview. Max 85 chars. --}}
    <div style="display:none;max-height:0;overflow:hidden;opacity:0;mso-hide:all;">
        Your password reset link — valid for {{ $expireMinutes }} minutes, one-time use only.
    </div>
@endsection

@section('content')
    <h2 class="email-text" style="color:#1f2937;font-size:24px;margin:0 0 20px 0;">Reset your password</h2>

    <p class="email-text" style="color:#4b5563;line-height:1.6;margin:0 0 15px 0;">
        Hi {{ $user->name }}, we received a request to reset the password for
        your Exospace account (<strong>{{ $user->email }}</strong>).
    </p>

    <p class="email-text" style="color:#4b5563;line-height:1.6;margin:0 0 25px 0;">
        Click the button below to choose a new password. The link works once
        and expires in <strong>{{ $expireMinutes }} minutes</strong>.
    </p>

    {{-- CTA button — table-based for Outlook --}}
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
        <tr>
            <td align="center" style="padding:10px 0 25px 0;">
                <a href="{{ $resetUrl }}"
                   style="background-color:#667eea;color:#ffffff;padding:14px 28px;text-decoration:none;border-radius:6px;font-weight:600;display:inline-block;">
                    Choose a new password
                </a>
            </td>
        </tr>
    </table>

    <p class="email-muted" style="font-size:13px;color:#9ca3af;line-height:1.6;margin:0 0 20px 0;">
        If the button doesn't work, copy and paste this URL into your browser:<br>
        <a href="{{ $resetUrl }}" style="color:#667eea;word-break:break-all;">{{ $resetUrl }}</a>
    </p>

    <p class="email-text" style="color:#4b5563;line-height:1.6;margin:0;">
        <strong>Didn't request this?</strong> You can safely ignore this email —
        your password stays unchanged until you follow the link. If you keep
        receiving these emails, please contact support.
    </p>
@endsection
