{{-- VERIFICATION-ITERATION FIX: branded email-verification email. Uses the
    shared table-based layout (Outlook/Gmail compatible, inline CSS) like
    every other Exospace transactional email. The verification URL is
    generated by Laravel's signed-URL machinery
    (App\Notifications\Auth\VerifyEmail) and is passed in ready-to-use —
    this view never builds URLs itself. --}}
@extends('emails.partials.layout')

@section('title', 'Confirm Your Email Address')

@section('preheader')
    {{-- Hidden but visible in inbox preview. Max 85 chars. --}}
    <div style="display:none;max-height:0;overflow:hidden;opacity:0;mso-hide:all;">
        Confirm your email address — this link expires in {{ $expireMinutes }} minutes.
    </div>
@endsection

@section('content')
    <h2 class="email-text" style="color:#1f2937;font-size:24px;margin:0 0 20px 0;">Confirm your email address</h2>

    <p class="email-text" style="color:#4b5563;line-height:1.6;margin:0 0 15px 0;">
        Hi {{ $user->name }}, welcome to Exospace! Please confirm that
        <strong>{{ $user->email }}</strong> is your email address to activate
        your account.
    </p>

    <p class="email-text" style="color:#4b5563;line-height:1.6;margin:0 0 25px 0;">
        Click the button below to verify your email. The link expires in
        <strong>{{ $expireMinutes }} minutes</strong>.
    </p>

    {{-- CTA button — table-based for Outlook --}}
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
        <tr>
            <td align="center" style="padding:10px 0 25px 0;">
                <a href="{{ $verificationUrl }}"
                   style="background-color:#667eea;color:#ffffff;padding:14px 28px;text-decoration:none;border-radius:6px;font-weight:600;display:inline-block;">
                    Verify my email address
                </a>
            </td>
        </tr>
    </table>

    <p class="email-muted" style="font-size:13px;color:#9ca3af;line-height:1.6;margin:0 0 20px 0;">
        If the button doesn't work, copy and paste this URL into your browser:<br>
        {{-- The href above keeps {{ }} escaping (correct &amp; in HTML). The
             VISIBLE copy-paste text must show a clean literal URL — the
             signed URL contains "&", which {{ }} would render as "&amp;".
             Safe: the value is app-generated (signed URL), never user input. --}}
        <a href="{{ $verificationUrl }}" style="color:#667eea;word-break:break-all;">{!! $verificationUrl !!}</a>
    </p>

    <p class="email-text" style="color:#4b5563;line-height:1.6;margin:0 0 20px 0;">
        Once you're verified you can build immersive 3D galleries, share them
        with a single link, and track views in real time.
    </p>

    <p class="email-text" style="color:#4b5563;line-height:1.6;margin:0;">
        <strong>Didn't create an account?</strong> You can safely ignore this
        email — no account will be activated. If you keep receiving these
        emails, please contact support.
    </p>
@endsection
