<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * M-10: Invoice model — stores customer invoice records + PDF paths.
 *
 * Iteration-008 (2CO-7 + O-10): Added VAT compliance fields:
 *   - customer_vat_number: customer's VAT/GST ID (B2B)
 *   - supplier_vat_number: supplier's VAT ID (snapshot)
 *   - tax_country_code: ISO country code the tax was charged under
 *   - reverse_charge: true if reverse-charge accounting applies
 *
 * Each successful payment (one-time or recurring) gets an Invoice record.
 * The PDF is generated by InvoiceGenerator service and stored at pdf_path.
 *
 * Tax compliance: the tax_amount + tax_rate fields support VAT/GST
 * invoicing requirements. The billing_address field supports B2B
 * invoicing where the customer's address is required on the invoice.
 *
 * The invoice_number is sequential per year (e.g. INV-2026-00001) and
 * unique across the whole table. It's generated by InvoiceGenerator
 * using a DB-level atomic counter.
 */
class Invoice extends Model
{
    use HasFactory;

    /** @var class-string<\Database\Factories\InvoiceFactory> */
    protected static string $factory = \Database\Factories\InvoiceFactory::class;

    protected $fillable = [
        'user_id',
        'transaction_id',
        'invoice_number',
        'amount',
        'tax_amount',
        'tax_rate',
        'currency',
        'plan',
        // ITERATION-1 FIX: how this purchase bills — 'subscription' or
        // 'one_time'. Set at creation from webhook context; the old PDF
        // detection read a non-existent transactions.subscription_id column
        // and mislabelled every renewal invoice as lifetime.
        'billing_type',
        'customer_name',
        'customer_email',
        'billing_address',
        'customer_vat_number',
        'supplier_vat_number',
        'tax_country_code',
        'reverse_charge',
        'pdf_path',
        'issued_at',
    ];

    protected $casts = [
        'amount'          => 'decimal:2',
        'tax_amount'      => 'decimal:2',
        'tax_rate'        => 'decimal:2',
        'reverse_charge'  => 'boolean',
        'issued_at'       => 'datetime',
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function transaction(): BelongsTo
    {
        return $this->belongsTo(Transaction::class);
    }

    /**
     * Format the subtotal (amount excluding tax) for display.
     */
    public function formattedSubtotal(): string
    {
        return number_format((float) $this->amount - (float) $this->tax_amount, 2) . ' ' . $this->currency;
    }

    /**
     * Format the tax amount for display.
     */
    public function formattedTax(): string
    {
        return number_format((float) $this->tax_amount, 2) . ' ' . $this->currency;
    }

    /**
     * Format the total (amount including tax) for display.
     */
    public function formattedTotal(): string
    {
        return number_format((float) $this->amount, 2) . ' ' . $this->currency;
    }

    /**
     * Iter-008: Whether this invoice has any VAT/tax content (for PDF
     * rendering — hide the tax block entirely if no tax was charged).
     */
    public function hasTax(): bool
    {
        return (float) $this->tax_amount > 0 || (bool) $this->reverse_charge;
    }
}
