<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * M-10: Invoice model — stores customer invoice records + PDF paths.
 *
 * Each successful payment (one-time or recurring) gets an Invoice record.
 * The PDF is generated by InvoiceGenerator service and stored at pdf_path.
 *
 * Tax compliance: the tax_amount + tax_rate fields support VAT/GST
 * invoicing requirements. The billing_address field supports B2B
 * invoicing where the customer's address is required on the invoice.
 *
 * The invoice_number is sequential per year (e.g. INV-2026-00001) and
 * unique across the whole table. It's generated by InvoiceGenerator
 * using a DB-level atomic counter.
 */
class Invoice extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'transaction_id',
        'invoice_number',
        'amount',
        'tax_amount',
        'tax_rate',
        'currency',
        'plan',
        'customer_name',
        'customer_email',
        'billing_address',
        'pdf_path',
        'issued_at',
    ];

    protected $casts = [
        'amount'      => 'decimal:2',
        'tax_amount'  => 'decimal:2',
        'tax_rate'    => 'decimal:2',
        'issued_at'   => 'datetime',
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function transaction(): BelongsTo
    {
        return $this->belongsTo(Transaction::class);
    }

    /**
     * Format the subtotal (amount excluding tax) for display.
     */
    public function formattedSubtotal(): string
    {
        return number_format((float) $this->amount - (float) $this->tax_amount, 2) . ' ' . $this->currency;
    }

    /**
     * Format the tax amount for display.
     */
    public function formattedTax(): string
    {
        return number_format((float) $this->tax_amount, 2) . ' ' . $this->currency;
    }

    /**
     * Format the total (amount including tax) for display.
     */
    public function formattedTotal(): string
    {
        return number_format((float) $this->amount, 2) . ' ' . $this->currency;
    }
}
